services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: fundo_sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Fundo@12345"
    ports:
      - "1433:1433"

  api:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    container_name: fundo_api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RunSeed: "true"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=FundoDB;User=sa;Password=Fundo@12345;TrustServerCertificate=True;Encrypt=False"
    ports:
      - "5001:80"
